name = "calcularq"
compatibility_date = "2026-02-20"

pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "calcularq"
database_id = "09b56d30-8386-41c4-9f29-f360d4a42a4b"
